# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.5"

[buildpack]
id       = "paketo-buildpacks/sap-machine"
name     = "Paketo SapMachine Buildpack"
version  = "{{.version}}"
homepage = "https://github.com/paketo-buildpacks/sap-machine"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[metadata.configurations]]
name        = "BPL_JVM_HEAD_ROOM"
description = "the headroom in memory calculation"
default     = "0"
launch      = true

[[metadata.configurations]]
name        = "BPL_JVM_LOADED_CLASS_COUNT"
description = "the number of loaded classes in memory calculation"
default     = "35% of classes"
launch      = true

[[metadata.configurations]]
name        = "BPL_JVM_THREAD_COUNT"
description = "the number of threads in memory calculation"
default     = "250"
launch      = true

[[metadata.configurations]]
name        = "BP_JVM_VERSION"
description = "the Java version"
default     = "11"
build       = true

[[metadata.configurations]]
name        = "JAVA_TOOL_OPTIONS"
description = "the JVM launch flags"
launch      = true

[[metadata.dependencies]]
id      = "jdk"
name    = "SapMachine JDK"
version = "11.0.11"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.11/sapmachine-jdk-11.0.11_linux-x64_bin.tar.gz"
sha256  = "a23cff74ffbd36b25706664d2f2d5eb7720f17b0f1b0e9311f6fc466057d6609"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jre"
name    = "SapMachine JRE"
version = "11.0.11"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.11/sapmachine-jre-11.0.11_linux-x64_bin.tar.gz"
sha256  = "119305a845b18b302324dfbc9cb341110127255185689af902219c3be0fa3b5a"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jdk"
name    = "SapMachine JDK"
version = "15.0.2"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-15.0.2/sapmachine-jdk-15.0.2_linux-x64_bin.tar.gz"
sha256  = "8b548fdaa37c4ab15cb91ca8078424f920d117076ff3f5734db3dd0bd74abb65"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jre"
name    = "SapMachine JRE"
version = "15.0.2"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-15.0.2/sapmachine-jre-15.0.2_linux-x64_bin.tar.gz"
sha256  = "aff5cc06743f61579de2e87d2b3978e89ebf7a5b068d799287a448d4eca0e97e"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

[[metadata.dependencies]]
id      = "jdk"
name    = "SapMachine JDK"
version = "16.0.1"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-16.0.1/sapmachine-jdk-16.0.1_linux-x64_bin.tar.gz"
sha256  = "a9b0a5748909b94ff8956572d32162147f7fd6e4a8878a6a06611e13c1897f44"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jre"
name    = "SapMachine JRE"
version = "16.0.0"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-16/sapmachine-jre-16_linux-x64_bin.tar.gz"
sha256  = "38addbe1d1e3278de79a2f4e485325e9ef9f4def45657c43975a7c07de7dfcf9"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jvmkill"
name    = "JVMKill Agent"
version = "1.16.0"
uri     = "https://github.com/cloudfoundry/jvmkill/releases/download/v1.16.0.RELEASE/jvmkill-1.16.0-RELEASE.so"
sha256  = "a3092627b082cb3cdbbe4b255d35687126aa604e6b613dcda33be9f7e1277162"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jvmkill/blob/main/LICENSE"

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "bin/helper",
  "bin/main",
  "buildpack.toml",
]
