# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.4"

[buildpack]
id       = "paketo-buildpacks/sap-machine"
name     = "Paketo SapMachine Buildpack"
version  = "{{.version}}"
homepage = "https://github.com/paketo-buildpacks/sap-machine"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[metadata.configurations]]
name        = "BPL_JVM_HEAD_ROOM"
description = "the headroom in memory calculation"
default     = "0"
launch      = true

[[metadata.configurations]]
name        = "BPL_JVM_LOADED_CLASS_COUNT"
description = "the number of loaded classes in memory calculation"
default     = "35% of classes"
launch      = true

[[metadata.configurations]]
name        = "BPL_JVM_THREAD_COUNT"
description = "the number of threads in memory calculation"
default     = "250"
launch      = true

[[metadata.configurations]]
name        = "BP_JVM_VERSION"
description = "the Java version"
default     = "11.*"
build       = true

[[metadata.configurations]]
name        = "JAVA_TOOL_OPTIONS"
description = "the JVM launch flags"
launch      = true

[[metadata.dependencies]]
id      = "jdk"
name    = "SapMachine JDK"
version = "11.0.9"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.9%2B9/sapmachine-jdk-11.0.9-ea.9_linux-x64_bin.tar.gz"
sha256  = "525287d686ff8454967b64137ec12f27f13a31e1376337f70b32ed57f74b242a"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

[[metadata.dependencies.licenses]]
type = "GPL-2.0 WITH Classpath-exception-2.0"
uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jre"
name    = "SapMachine JRE"
version = "11.0.9"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.9%2B8/sapmachine-jre-11.0.9-ea.8_linux-x64_bin.tar.gz"
sha256  = "cd8c6aae418caeef75e0b8ae14b542db5b3fe7f43fbfd3be2b7a2cadd604b8fa"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jdk"
name    = "SapMachine JDK"
version = "14.0.2"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-14.0.2/sapmachine-jdk-14.0.2_linux-x64_bin.tar.gz"
sha256  = "59d7b4b9866a3f9108937161ae9d9bc3885d4bab3f2ffac334c2170a258b7258"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

[[metadata.dependencies.licenses]]
type = "GPL-2.0 WITH Classpath-exception-2.0"
uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jre"
name    = "SapMachine JRE"
version = "14.0.2"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-14.0.2%2B12/sapmachine-jre-14.0.2-ea.12_linux-x64_bin.tar.gz"
sha256  = "1e12cd6c50de6e785cb73004aeede2c5251d3f6bf781d00500999dd7d27617fb"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jdk"
name    = "SapMachine JDK"
version = "15.0.0"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-15%2B10/sapmachine-jdk-15-ea.10_linux-x64_bin.tar.gz"
sha256  = "255012c54e984ff6a00f44a1d756e568ab46b4a2ba5caf93673cc3baaffac6cd"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

[[metadata.dependencies.licenses]]
type = "GPL-2.0 WITH Classpath-exception-2.0"
uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jre"
name    = "SapMachine JRE"
version = "15.0.0"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-15%2B19/sapmachine-jre-15-ea.19_linux-x64_bin.tar.gz"
sha256  = "1d1834b83ca40449b8bf78f5a6549ca0a82a0ae2f6ebc579df3e42f6a05147bd"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jvmkill"
name    = "JVMKill Agent"
version = "0.0.0"
uri     = "placeholder"
sha256  = "placeholder"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jvmkill/blob/main/LICENSE"

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "bin/helper",
  "bin/main",
  "buildpack.toml",
]
