# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.6"

[buildpack]
id       = "paketo-buildpacks/sap-machine"
name     = "Paketo SapMachine Buildpack"
version  = "{{.version}}"
homepage = "https://github.com/paketo-buildpacks/sap-machine"
description = "A Cloud Native Buildpack that provides the SAP Machine implementations of JREs and JDKs"
keywords    = ["java", "jvm", "jre", "jdk"]

[[buildpack.licenses]]
type = "Apache-2.0"
uri  = "https://github.com/paketo-buildpacks/sap-machine/blob/main/LICENSE"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.paketo.stacks.tiny"

[[stacks]]
id = "*"

[[metadata.configurations]]
name        = "BPL_JVM_HEAD_ROOM"
description = "the headroom in memory calculation"
default     = "0"
launch      = true

[[metadata.configurations]]
name        = "BPL_JVM_LOADED_CLASS_COUNT"
description = "the number of loaded classes in memory calculation"
default     = "35% of classes"
launch      = true

[[metadata.configurations]]
name        = "BPL_JVM_THREAD_COUNT"
description = "the number of threads in memory calculation"
default     = "250"
launch      = true

[[metadata.configurations]]
name        = "BPL_HEAP_DUMP_PATH"
description = "write heap dumps on error to this path"
default     = ""
launch      = true

[[metadata.configurations]]
name        = "BPL_JAVA_NMT_ENABLED"
description = "enables Java Native Memory Tracking (NMT)"
default     = "true"
launch      = true

[[metadata.configurations]]
name        = "BPL_JAVA_NMT_LEVEL"
description = "configure level of NMT, summary or detail"
default     = "summary"
launch      = true

[[metadata.configurations]]
name        = "BPL_JMX_ENABLED"
description = "enables Java Management Extensions (JMX)"
default     = "false"
launch      = true

[[metadata.configurations]]
name        = "BPL_JMX_PORT"
description = "configure the JMX port"
default     = "5000"
launch      = true

[[metadata.configurations]]
name        = "BPL_DEBUG_ENABLED"
description = "enables Java remote debugging support"
default     = "false"
launch      = true

[[metadata.configurations]]
name        = "BPL_DEBUG_PORT"
description = "configure the remote debugging port"
default     = "8000"
launch      = true

[[metadata.configurations]]
name        = "BPL_DEBUG_SUSPEND"
description = "configure whether to suspend execution until a debugger has attached"
default     = "false"
launch      = true

[[metadata.configurations]]
name        = "BP_JVM_VERSION"
description = "the Java version"
default     = "11"
build       = true

[[metadata.configurations]]
name        = "BP_JVM_TYPE"
description = "the JVM type - JDK or JRE"
default     = "JRE"
build       = true

[[metadata.configurations]]
name        = "JAVA_TOOL_OPTIONS"
description = "the JVM launch flags"
launch      = true

[[metadata.dependencies]]
id      = "jdk"
name    = "SapMachine JDK"
version = "11.0.12"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.12/sapmachine-jdk-11.0.12_linux-x64_bin.tar.gz"
sha256  = "f999dd243d00ee037ade946ed9c6c13217636666f4e433f019b635df6eab8f5c"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jre"
name    = "SapMachine JRE"
version = "11.0.12"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.12/sapmachine-jre-11.0.12_linux-x64_bin.tar.gz"
sha256  = "8d79c1881f1e826b2b0b0bf082f0c4cd0086d9be78808a04b9a17bf37af133a0"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jdk"
name    = "SapMachine JDK"
version = "16.0.2"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-16.0.2/sapmachine-jdk-16.0.2_linux-x64_bin.tar.gz"
sha256  = "43831d4ebb9cd6ec9cf6f992406b290b3da409af21cd61b37d80e8a051c1a998"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jre"
name    = "SapMachine JRE"
version = "16.0.2"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-16.0.2/sapmachine-jre-16.0.2_linux-x64_bin.tar.gz"
sha256  = "4b0bcb0a15813077a7ecaf3c21041f80f524b759471b9e971896ed7cbc8d58a8"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jdk"
name    = "SapMachine JDK"
version = "17.0.0"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-17/sapmachine-jdk-17_linux-x64_bin.tar.gz"
sha256  = "0d1eb78051983ade81b7190150329c53c866d44a7416acf7c6f9a6f5c9da595e"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jre"
name    = "SapMachine JRE"
version = "17.0.0"
uri     = "https://github.com/SAP/SapMachine/releases/download/sapmachine-17/sapmachine-jre-17_linux-x64_bin.tar.gz"
sha256  = "4e0955f39519947c184d40b71871b4a7f0c343043bbd3e5e0b041cc00d70bd05"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "bin/helper",
  "bin/main",
  "buildpack.toml",
]
